### ISSUE TITLE
Fails to build in Release mode on macOS 10.13.4/Xcode 9.3

### ISSUE THREAD

**Issue by zhuowei** [amzn/ion-c#106]
I tried building ion-c: the debug build works fine (./build-debug.sh) but the release build fails with the error:

```
[ 71%] Linking CXX executable all_tests
Undefined symbols for architecture x86_64:
  "join_path(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      __GLOBAL__sub_I_test_vectors.cpp in test_vectors.cpp.o
      IonCli_ProcessBasic_Test::TestBody() in test_ion_cli.cpp.o
      IonCli_CompareNullsBasic_Test::TestBody() in test_ion_cli.cpp.o
      IonCli_CompareListsEquivs_Test::TestBody() in test_ion_cli.cpp.o
      IonCli_CompareSexpsNonequivs_Test::TestBody() in test_ion_cli.cpp.o
      IonCli_CompareAnnotatedIvmsEmbeddedNonequivs_Test::TestBody() in test_ion_cli.cpp.o
      IonCli_CompareMultipleInputFiles_Test::TestBody() in test_ion_cli.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/all_tests] Error 1
make[1]: *** [test/CMakeFiles/all_tests.dir/all] Error 2
make: *** [all] Error 2
```

I'm using the latest master branch (0903060fdc83c1c931aa9530d52b4a9ba9491e37), macOS 10.13.4, the Clang that came with Xcode 9.3, and latest CMake from Homebrew:

```
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ cmake --version
cmake version 3.11.2
```

**Comment by tgregg** [comment]
@zhuowei Thanks for the report. I'm looking into this.

**Comment by tgregg** [comment]
I was able to reproduce the issue on my machine, and solved it by removing some inline declarations for shared functions. For some reason, the linking behavior for these differed between build configurations.

I also updated our Travis and AppVeyor config to build and test both the debug and the release configuration, which should prevent this from happening again.

@zhuowei If this doesn't solve your problem please let us know.

**Comment by zhuowei** [comment]
@tgregg Removing the `inline` was the workaround I used locally, so it should work.

Thank you so much for the prompt response and fix!
